### ISSUE TITLE
TypeError: Cannot create property 'type' on string 'reserved fields (2, 3) must be empty'

### ISSUE THREAD

**Issue by evbogue** [dominictarr/ssb-ws#2]
Here's the other error bringing my pub down when I have the lite client connected

```
/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot create property 'type' on string 'reserved fields (2, 3) must be empty'
    at WebSocket.onError (/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.onerror (/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/Receiver.js:190:12)
    at Receiver.add (/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/home/ev/.ssb/node_modules/ssb-ws/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by dominictarr** [comment]
I updated pull-ws to use latest ws@1.1.0,
can you update and see if it fixes this?

**Comment by evbogue** [comment]
I haven't had this happen again, assuming it's fixed.
